### ISSUE TITLE
Double trouble

### ISSUE THREAD

**Issue by dwillmore** [Montecri/PiOnPi#1]
More a discussion topic than an issue, but I wanted to point out that the code uses the double type and really means it.  If you try to use it on an AVR arduino, double gets demoted to float and this code will break.  It may be possible to change it to work with float instead (calculating fewer digits at a time), but it's unlikely to work as-is.

Just a warning to others trying to port the code to platforms without a real double type.

**Comment by Montecri** [comment]
Great point! Will put a disclaimer on README.

Thank you!
